name: Create ZIP Archive and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Необходим для работы с тегами

    - name: Get latest tag
      id: get_tag
      run: echo "NEW_VERSION=v1.0" >> $GITHUB_ENV

    - name: Create new tag
      run: |
        git tag ${{ env.NEW_VERSION }}
        git push origin ${{ env.NEW_VERSION }}

    - name: Create ZIP archive
      run: |
        zip -r tg_bot.zip * -x "*.git*" ".env" ".gitignore" "credentials.json" ".github/*"

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.NEW_VERSION }}
        release_name: "tg_bot release ${{ env.NEW_VERSION }}"
        draft: false
        prerelease: false

    - name: Upload ZIP to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: tg_bot.zip
        asset_name: tg_bot.zip
        asset_content_type: application/zip